run_join_thread:
	gcc -lpthread -o prog join_thread.c && ./prog

run_shared_variable:
	gcc -lpthread -o prog shared_variable.c && ./prog

run_shared_variable_semaphore:
	gcc -lpthread -o prog shared_variable_semaphore.c && ./prog

run_signal_cleanup:
	gcc -lpthread -o prog signal_cleanup.c && ./prog